### ISSUE TITLE
Enhance add project dialog UI

### ISSUE THREAD

**Issue by aditiapratama** [armadillica/flamenco#106]
This is intended to simplify the dialog for adding the projects. Below is only the mockup, let me know what do you think.

![add_project_ui](https://cloud.githubusercontent.com/assets/982553/6395393/70b61362-be0a-11e4-8960-1c90de33fa2f.png)

**Comment by fsiddi** [comment]
Hey there,
currently projects are not well structured and we plan to hold them off for a bit until the next big merge we are working on.

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
