### ISSUE TITLE
Switching Styles for brender

### ISSUE THREAD

**Issue by cyprusglobe** [armadillica/flamenco#11]
I have been looking at http://semantic-ui.com/

and their UI looks amazing im wondering if you guys want to switch to this?

just a question cause i really like the way http://semantic-ui.com/ looks

let me know 

Thanks

Kelvin

**Comment by sybrenstuvel** [comment]
We're working on a new Flamenco. This version will be integrated into the Pillar framework, which has its own UI for the Cloud & Attract already.
