### ISSUE TITLE
Add job from dashboard is broken

### ISSUE THREAD

**Issue by ClemPi** [armadillica/flamenco#118]
When trying to add a job using the dashboard an error occurs in the server.

`Cant find module application.job_compilers.None: No module named None.` this come from `server/application/modules/tasks/__init__.py:79`.

The error occur when setting job type to simple or tiled.

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
