### ISSUE TITLE
FileNotFoun: /tmp/job.zip

### ISSUE THREAD

**Issue by tobimai** [armadillica/flamenco#138]
When I press "Save and send" in Blender, then just a error message pops up which says:

Traceback:
File "/home/ubuntu/.config/blender/2.74/scripts/addons/render_flamenco.py" , line 230 in execute ('jobfile.zip', open (zippath, 'rb'),
FileNotFoundError: [Error 2] No such file or directory: '/tmp/job.zip'

location: <unknown location>: -1

I hope someone can help me.

**Comment by fsiddi** [comment]
Hello,
are you using the latest version available? Where did you save the blend file you want to submit?

**Comment by tobimai** [comment]
OK I used the latest version, I saved the file in my home directory, but Yesterday I reinstalled my Ubuntu, and now I get this error whenever I try to start the manager:

TypeError: <flask_script.commands.Command object at 0xb644cc6c>: tuple indices must be integers, not str

I don't know why, its exactly the same ubuntu 15.04 than before. Should I open a new issue for that?

**Comment by fsiddi** [comment]
I'm not sure about that. I would open another issue. Make sure you check out the server terminal for errors.

**Comment by Eibriel** [comment]
Hi @tobimai do you have BAM client?

**Comment by tobimai** [comment]
Yes i ran sudo apt-get install bam
I think that works? Or do i have to set the bam client up manually?

**Comment by fsiddi** [comment]
@tobimai you should to `pip3 install blender-bam`. Let me know if it works!

**Comment by tobimai** [comment]
Oh ok I think thats the problem. But i cant test it now because of this 

https://github.com/armadillica/flamenco/issues/140

**Comment by fsiddi** [comment]
Hi @tobimai, the blocking issue has been fixed. Let me know if I can close this issue as well.

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
