### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by rossgibb** [armadillica/flamenco#139]
The migration file  flamenco/flamenco/server/migrations/versions/3a2606d017ea_removing_tasks_count_tasks_completed.py

Does not seem to be compatible with sqllite. Is sqllite still supported?

```
INFO  [alembic.migration] Running upgrade 4bb5c8ca790e -> 3a2606d017ea, Removing tasks_count tasks_completed
Traceback (most recent call last):
  File "manage.py", line 78, in <module>
    manager.run()

...

  File "/home/rg/dev/flamenco/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (OperationalError) near "DROP": syntax error u'ALTER TABLE job DROP COLUMN tasks_count' ()
```

I don't think Sqllite suports dropping columns from tables.

**Comment by fsiddi** [comment]
You are right.
In order to keep supporting SQLite we have to edit the migrations. I'll look into that as soon as possible. We might even consider resetting the migrations entirely.

**Comment by rcarmo** [comment]
This would be nice. SQLite is still a lot less hassle than MySQL for small setups, and I'd like to see it working out of the box (I'm used to tuning SQLite with WAL mode for concurrent writes, and cringe somewhat at having to set up MySQL for very small databases...)

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
