### ISSUE TITLE
error manager runserver

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#142]
Traceback (most recent call last):
  File "./manage.py", line 5, in <module>
    import requests
ImportError: No module named requests

**Comment by fsiddi** [comment]
Are you running the command with the virtual environment activated?

**Comment by antonvdh** [comment]
Oeps ut then my mistake sorry for that.
But Then I still cannot run manager server after setting the linux path /mnt/blender-2-74/ I get this messsage
TypeError: <flask_script.commands.Command object at 0x7f7073bfe0d0>: 'value' is an invalid keyword argument for JobType

**Comment by lolzballs** [comment]
Sorry, @antonvdh did you manage to get this working?

I have tried setting the path to /usr/bin/blender but I still get this error:
> 'value' is an invalid keyword argument for JobType

Any help would be appreciated!

**Comment by antonvdh** [comment]
I had no time for testing this week because my father died.
Op 25 jun. 2015 21:50 schreef "Benjamin Cheng" <notifications@github.com>:
