### ISSUE TITLE
(Manager) TypeError: 'value' is an invalid keyword argument for JobType when first using/configuring a database

### ISSUE THREAD

**Issue by stefankamoda** [armadillica/flamenco#145]
After creating a new MySQL database and configuring the manager to use it (via config.py) running 

flamenco/manager/python manage.py runserver

results in "'value' is an invalid keyword argument for JobType" after entering the Blender paths for Linux, OSX and Windows. In manager/manage.py (line 71) a JobType is created with

render_config = JobType(
            name='simple_blender_render',
            *value*=json.dumps(configuration))

but JobType doesn't define a value property, I was able to get the manager to start without errors by changing it (and similiar code on line 91) to

render_config = JobType(
            name='simple_blender_render',
            *properties*=json.dumps(configuration))

After this change the manager starts fine but I'm not sure if this is correct. I was able to reproduce the error and the "fix" on both Linux and Windows.

**Comment by antonvdh** [comment]
Did you solve this problem I keep getting this message:

TypeError: <flask_script.commands.Command object at 0x7f97a671d210>: 'value' is an invalid keyword argument for JobType
