### ISSUE TITLE
Blender addon: Failed to remove BAM archive

### ISSUE THREAD

**Issue by callym** [armadillica/flamenco#150]
When I try to manually delete the file, Windows Explorer says that the file is open in Blender, even though it should have been closed automatically at the end of this loop

``` python
with open(zippath, 'rb') as f:
                print ("Sending {0} file to server...".format(
                    humansize(statinfo.st_size)))
                p = requests.post(server_job_file_url, data=f)
```

**Comment by fsiddi** [comment]
Is there a specific reason why you want to delete the file manually? Is the script failing to delete it? I afraid I can't help with Windows, but my guess is that as long as the Python process in Blender is not stopped, you won't be able to delete the file.

Did you try to close Blender and delete the file?

**Comment by Eibriel** [comment]
This sounds like a Windows issue. Any further info @callym ?

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
