### ISSUE TITLE
Dashboard is not working  TemplateNotFound: layout.html

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#163]
File "/srv/www/htdocs/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: layout.html

looked into
/flamenco/dashboard/application/templates/
There is no layout.html !?

**Comment by peppelinux** [comment]
# dashboard dependencies
cd flamenco/dashboard

# this is needed only on wheezy distribution
sudo echo "deb http://ftp.us.debian.org/debian wheezy-backports main" >> /etc/apt/sources.list
sudo apt-get update

# On linux you can install NodeJS using the package manager.
sudo apt-get install nodejs nodejs-legacy curl
sudo curl -L --insecure https://www.npmjs.org/install.sh | bash
sudo npm install -g grunt-cli
sudo apt-get install ruby
sudo gem install sass
sudo npm install
grunt

**Comment by antonvdh** [comment]
Already installed NodeJS on my linux system.
I will reinstall thanks.
Op 3 okt. 2015 10:55 schreef "peppelinux" <notifications@github.com>:

**Comment by antonvdh** [comment]
Installed as described without errors on openSuse (apt-get is zypper).
But when starting grunt 
(venv)root@linux-nfs:/srv/www/htdocs/flamenco/flamenco/dashboard> grunt
Running "sass:dist" (sass) task
Warning: 
You need to have Ruby and Sass installed and in your PATH for this task to work.                                                             
More info: https://github.com/gruntjs/grunt-contrib-sass                                                                                     
 Use --force to continue.  
 -----------------------------------------------------------------------------------------------
(venv)root@linux-nfs:/srv/www/htdocs/flamenco/flamenco/dashboard> grunt --force
Running "sass:dist" (sass) task
Warning: 
You need to have Ruby and Sass installed and in your PATH for this task to work.                                                             
More info: https://github.com/gruntjs/grunt-contrib-sass                                                                                     
 Used --force, continuing.
Warning: spawn sass ENOENT Used --force, continuing.

Running "autoprefixer:no_dest" (autoprefixer) task
File application/static/css/main.css created.

Running "jade:compile" (jade) task
>> 6 files created.

Done, but with warnings.
(venv)root@linux-nfs:/srv/www/htdocs/flamenco/flamenco/dashboard> ./manage.py runserver
 * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
 * Restarting with stat
--------------------------------------------------------------------
Flamenco dashboard is now running well in Firefox.
