### ISSUE TITLE
Worker job failed Errno 2] No such file or directory

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#165]
When starting a simple cube animation job the worker failed  need some help.
```
New Task Found 12, job 1
Fetching job file 1
Extracting /tmp/flamenco-worker-linux-nfs/1/taskfile_1.zip
Fetching support file 1
Extracting /tmp/flamenco-worker-linux-nfs/1/tasksupportfile_1.zip
Fetching dependency http://192.168.178.18:7777/static/storage/1/dependencies_12.zip
Extracting /tmp/flamenco-worker-linux-nfs/1/dependencies.zip
Removing bad zipfile /tmp/flamenco-worker-linux-nfs/1/dependencies.zip
ERROR:root:Not a ZipFile
200
Running:
/NFS/blender-2.75a/blender
--enable-autoexec
-noaudio
--background
/tmp/flamenco-worker-linux-nfs/1/1//blenderblok.blend
--render-output
/tmp/flamenco-worker-linux-nfs/1/output/12/#####
--python
/tmp/flamenco-worker-linux-nfs/1/1//pre_render.py
--render-format
PNG
--frame-start
56
--frame-end
60
--render-anim
Traceback (most recent call last):
  File "./manage.py", line 67, in <module>
    manager.run()
  File "/srv/www/htdocs/flamenco/flamenco/venv/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/srv/www/htdocs/flamenco/flamenco/venv/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/srv/www/htdocs/flamenco/flamenco/venv/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "./manage.py", line 52, in runserver
    controllers.worker_loop()
  File "/srv/www/htdocs/flamenco/flamenco/worker/application/controllers.py", line 273, in worker_loop
    execute_task(task, files)
  File "/srv/www/htdocs/flamenco/flamenco/worker/application/controllers.py", line 759, in execute_task
    run_blender_in_thread(options)
  File "/srv/www/htdocs/flamenco/flamenco/worker/application/controllers.py", line 528, in run_blender_in_thread
    stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
(venv)anton@linux-nfs:/srv/www/htdocs/flamenco/flamenco/worker> 
```

**Comment by Eibriel** [comment]
Hi! Is Blender on /NFS/blender-2.75a/blender path on the worker? It have execution permissions?

**Comment by antonvdh** [comment]
Yes I have changed it now in /mnt/blender-2.75a/blender to get permissions.
And gave it another try. 

Running:
/mnt/blender-2.75a/blender
--enable-autoexec
-noaudio
--background
/tmp/flamenco-worker-linux-nfs/1/1//blenderblok.blend
--render-output
/tmp/flamenco-worker-linux-nfs/1/output/24/#####
--python
/tmp/flamenco-worker-linux-nfs/1/1//pre_render.py
--render-format
PNG
--frame-start
47
--frame-end
48
--render-anim
Read new prefs: /home/anton/.config/blender/2.75/config/userpref.blend
found bundled python: /mnt/blender-2.75a/2.75/python
read blend: /tmp/flamenco-worker-linux-nfs/1/1//blenderblok.blend
Warning: Unable to open '/tmp/flamenco-worker-linux-nfs/1/1//blenderblok.blend': No such file or directory

**Comment by Eibriel** [comment]
And /tmp/flamenco-worker-linux-nfs/1/1/blenderblok.blend exists?

**Comment by antonvdh** [comment]
blenderblok.blend does not exist in   /tmp/flamenco-worker-linux-nfs/1/1

**Comment by antonvdh** [comment]
When I manual place the file it is running but no png file is placed in the output I told blender.
???
Fra:1 Mem:46.24M (0.00M, Peak 116.56M) | Mem:15.56M, Peak:17.81M | Scene, RenderLayer | Path Tracing Tile 15/15, Sample 100/100
Fra:1 Mem:46.24M (0.00M, Peak 116.56M) | Mem:15.56M, Peak:17.81M | Scene, RenderLayer | Finished
Fra:1 Mem:46.23M (0.00M, Peak 116.56M) Sce: Scene Ve:0 Fa:0 La:0

[]
Saved: /tmp/flamenco-worker-linux-nfs/1/output/1/00001.png
 Time: 00:06.44 (Saving: 00:00.59)

**Comment by Eibriel** [comment]
Its ok the place of the output png, Flamenco uses its own output folder. About the file not being sent, do you have BAM installed? How are you sending jobs to Flamenco?

**Comment by antonvdh** [comment]
What is BAM and why do i need that?
I am sending jobs with the flamenco plugin
works fine. Making projects jobs using the dashboard is not possible to
save.
Op 3 okt. 2015 19:38 schreef "Eibriel" <notifications@github.com>:

**Comment by peppelinux** [comment]
sudo pip3 install blender-bam

**Comment by antonvdh** [comment]
The output has to be set to a network place otherwise it is useless for us.
Op 3 okt. 2015 19:47 schreef "anton vandehaterd" <antonvdh@gmail.com>:

**Comment by antonvdh** [comment]
Is already installed
Op 3 okt. 2015 19:56 schreef ":)" <notifications@github.com>:

**Comment by peppelinux** [comment]
empty server and manager db.
restart with a clean setup.
take care of all the paths, control on the db.setting that all of those path were configured and working.
purge also /tmp for dead thumbails :)

**Comment by antonvdh** [comment]
Ok thanks sofar.
Please make it possible to set the output for us. It was working in the
alpha release.
Op 3 okt. 2015 20:03 schreef ":)" <notifications@github.com>:

**Comment by antonvdh** [comment]
Sorry did not fix the tmp problem. This is a new animation  I wanted to render
--------------------------------------------
-render-anim
Read new prefs: /home/anton/.config/blender/2.75/config/userpref.blend
found bundled python: /mnt/blender-2.75a/2.75/python
read blend: /tmp/flamenco-worker-linux-nfs/3/3//planes_rendertest.blend
Warning: Unable to open '/tmp/flamenco-worker-linux-nfs/3/3//planes_rendertest.blend': No such file or directory

**Comment by ZanQdo** [comment]
Same happens to me. Flamenco actually keeps pulling the *very first file* I ever rendered in flamenco and ignoring the actual current file (with different name and location). That file doesn't even exist anymore so I guess it's pulling from some cache folder that I don't know where it is.

**Comment by fsiddi** [comment]
Thanks for reporting this. I'll look into it asap.

**Comment by peppelinux** [comment]
I had in the past this kind of problem, the same problem.
To solve it I've just reconfigured all from scratch, now I cant remember the cause of this exception.
This happend with single image rendering or with tiled rendering ?

**Comment by ZanQdo** [comment]
Sequence o images

**Comment by antonvdh** [comment]
What is the best way to empty server and manager db.

**Comment by peppelinux** [comment]
in server folder:
rm server.sqlite

in manager folder:
rm manager.sqlite

remove all the dead thumbnails in /tmp
remove all the server and manager application/static/storage/*

in the future will manage our storage strategy in a more smart way, but if you understand how to get  it to work it's not so bad :) it simply works

**Comment by antonvdh** [comment]
Thanks 
I was already searching the right way to clean up  /tmp within opensuse 13.2 .

**Comment by ZanQdo** [comment]
@antonvdh I'm happy to find someone else using opensuse!

@peppelinux where is the application/static/storage/ path?

**Comment by peppelinux** [comment]
one for manager, one for server.
look inside their folder

**Comment by ZanQdo** [comment]
@peppelinux I see ok! Just to be sure before I launch yet another issue. We're supposed to run each service ($ ./manage.py runserver) from within the venv?

**Comment by peppelinux** [comment]
Yes, as usual.

It could be better to deploy a uwsgi gateway coupled with nginx for server, manager and dashboard and the service runlevel script, usable in worker dir, to run worker process as system startup process.

Whatever, for a lazy production context, you can execute each command manually

**Comment by ZanQdo** [comment]
Then huston we have a problem. I'll open a new issue :)

**Comment by ZanQdo** [comment]
Cheers, I finally catch up with with everybody else on issue 165 :)

**Comment by antonvdh** [comment]
@ZanQdo I enjoy working with openSUSE LXDE rendernodes and Flamenco.

**Comment by ZanQdo** [comment]
Any news on this error?

**Comment by fsiddi** [comment]
Sorry no news, I'm still busy with the Blender Cloud release.

**Comment by antonvdh** [comment]
Tested but see no improvement :-(

**Comment by philnelson** [comment]
Seeing this myself with OS X workers. Linux workers appear to be ok.

**Comment by fsiddi** [comment]
@philnelson could you paste a log please?

**Comment by philnelson** [comment]
Quering for a new task
New Task Found 14, job 2
Fetching job file 2
Extracting /var/folders/bf/68sw2jd524ddxlylb99msdmc0000gn/T/flamenco-worker/Phils-Laptop.local/2/taskfile_2.zip
Fetching support file 2
Extracting /var/folders/bf/68sw2jd524ddxlylb99msdmc0000gn/T/flamenco-worker/Phils-Laptop.local/2/tasksupportfile_2.zip
Fetching dependency for task 2
No file found
Running:
/usr/bin/blender
--enable-autoexec
-noaudio
--background
/var/folders/bf/68sw2jd524ddxlylb99msdmc0000gn/T/flamenco-worker/Phils-Laptop.local/2/2//mountain1.blend
--render-output
/var/folders/bf/68sw2jd524ddxlylb99msdmc0000gn/T/flamenco-worker/Phils-Laptop.local/2/output/14/#####
--python
/var/folders/bf/68sw2jd524ddxlylb99msdmc0000gn/T/flamenco-worker/Phils-Laptop.local/2/2//pre_render.py
--render-format
EXR
--frame-start
61
--frame-end
65
--render-anim
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    worker_loop()
  File "/Users/philnelson/Documents/Code/flamenco/flamenco/worker/application/controllers.py", line 238, in worker_loop
    execute_task(task, files)
  File "/Users/philnelson/Documents/Code/flamenco/flamenco/worker/application/controllers.py", line 721, in execute_task
    run_blender_in_thread(options)
  File "/Users/philnelson/Documents/Code/flamenco/flamenco/worker/application/controllers.py", line 491, in run_blender_in_thread
    stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
(venv)Phils-Laptop:worker philnelson$ vi /var/folders/bf/68sw2jd524ddxlylb99msdmc0000gn/T/flamenco-worker/Phils-Laptop.local/2/2//pre_render.py
(venv)Phils-Laptop:worker philnelson$ mate /Users/philnelson/Documents/Code/flamenco/flamenco/worker/application/controllers.py"

**Comment by philnelson** [comment]
I see several instances of `//` in the file paths. Is it possible some path info is being missed?

**Comment by fsiddi** [comment]
Usually the `//` is not an issue. A couple more questions:
* are you using latest master (of flamenco)?
* when you go to `/var/folders/bf/68sw2jd524ddxlylb99msdmc0000gn/T/flamenco-worker/Phils-Laptop.local/2` what do you see?
* how does your db currently look? Can you clean it up from all tasks and jobs?

**Comment by philnelson** [comment]
Latest master: yes.

`/var/folders/bf/68sw2jd524ddxlylb99msdmc0000gn/T/flamenco-worker/Phils-Laptop.local/2` definitely doesn't exist.

DB: Just removed the DBs entirely and tried again. Same result.

**Comment by fsiddi** [comment]
Ok, maybe we can try to debug this in IRC on the flamenco channel? I'll be online again in 10 hours or so.

**Comment by antonvdh** [comment]
solved
