### ISSUE TITLE
Requirements fail to install

### ISSUE THREAD

**Issue by ZanQdo** [armadillica/flamenco#166]
I'm getting this http://www.pasteall.org/61447 trying to follow the instructions:

install python deps (remember to `source bin/activate` first!)
pip install -r $FLAMENCODIR/requirements.txt

I'm not really sure what "remember to `source bin/activate` first!" is supposed to mean. I guess it means activate the venv first?

**Comment by Eibriel** [comment]
Yes, you need to activate the virtual environment
    . ./venv/bin/activate

**Comment by ZanQdo** [comment]
Thanks, then I'm doing that right, next is "pip install -r requirements.txt" from within flamenco? I suppose the $FLAMENCODIR part is just a placeholder?

**Comment by Eibriel** [comment]
Try going to the folder where requirements.txt is (inside flamenco) and run pip install -r requirements. txt

**Comment by ZanQdo** [comment]
@Eibriel thanks man, but I *think* I'm doing it correctly. Check out the whole log

http://www.pasteall.org/61454

**Comment by peppelinux** [comment]
http://stackoverflow.com/questions/14087598/python-3-3-importerror-no-module-named-configparser

**Comment by ZanQdo** [comment]
I see.. well I did:

pip install mysqlclient
pip2.7 install mysqlclient (this was missing)
pip3.4 install mysqlclient

still getting the same error. I'm not sure what to do inside the venv? I have to install again?

**Comment by peppelinux** [comment]
sudo aptitude install python3-pip libmysqlclient-dev build-essential python-dev libjpeg8 libjpeg8-dev libfreetype6 libfreetype6-dev zlib1g-dev python-pip

then 

source bin/activate in flamenco dir

then 

pip install -r requirements.txt

then

pip3 install blender-bam

read readme, Debian GNU/Linux setup

**Comment by ZanQdo** [comment]
Yeah I have read it and done it, I had everything installed exept libfreetype6-dev zlib1g-dev
I failed to mention I'm on latest Open Suse

then

source bin/activate in flamenco dir

"source bin/activate" didn't work so I did "source venv/bin/activate" and this is the result:

http://www.pasteall.org/61479

**Comment by peppelinux** [comment]
https://github.com/armadillica/flamenco/issues/166#issuecomment-145399498

**Comment by ZanQdo** [comment]
Python 2.7.8
&
Python 3.4.1

**Comment by peppelinux** [comment]
...and pip is for python2.7 or 3.4 ?
have you read the stackoverflow post ?

**Comment by ZanQdo** [comment]
I read it yes. I got python3-devel and libmysqlclient-devel installed. Also this is what the different pip commands return. It seems the problem is with "pip3.4 install MySQL-python"

zanqdo@linux-sao3:~> pip2.7 install mysqlclient
Requirement already satisfied (use --upgrade to upgrade): mysqlclient in /usr/lib64/python2.7/site-packages
Cleaning up...
zanqdo@linux-sao3:~> pip2.7 install MySQL-python
Requirement already satisfied (use --upgrade to upgrade): MySQL-python in /usr/lib64/python2.7/site-packages
Cleaning up...
zanqdo@linux-sao3:~> pip3.4 install mysqlclient
Requirement already satisfied (use --upgrade to upgrade): mysqlclient in /usr/lib64/python3.4/site-packages
Cleaning up...
zanqdo@linux-sao3:~> pip3.4 install MySQL-python
Downloading/unpacking MySQL-python
  Downloading MySQL-python-1.2.5.zip (108kB): 108kB downloaded
  Running setup.py (path:/tmp/pip_build_zanqdo/MySQL-python/setup.py) egg_info for package MySQL-python
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_zanqdo/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/tmp/pip_build_zanqdo/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ImportError: No module named 'ConfigParser'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_zanqdo/MySQL-python/setup.py", line 13, in <module>

    from setup_posix import get_config

  File "/tmp/pip_build_zanqdo/MySQL-python/setup_posix.py", line 2, in <module>

    from ConfigParser import SafeConfigParser

ImportError: No module named 'ConfigParser'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_zanqdo/MySQL-python
Storing debug log for failure in /home/zanqdo/.pip/pip.log

**Comment by ZanQdo** [comment]
Also tried the suggested method in the link it it says everything is already installed:

(venv)zanqdo@linux-sao3:~/Downloads/flamenco> sudo aptitude install python3-devel
Loading repository data...
Reading installed packages...
'python3-devel' is already installed.
No update candidate for 'python3-devel-3.4.1-4.2.1.x86_64'. The highest available version is already installed.
Resolving package dependencies...
(venv)zanqdo@linux-sao3:~/Downloads/flamenco> sudo aptitude install libmysqlclient-devel
Loading repository data...
Reading installed packages...
'libmysqlclient-devel' is already installed.
No update candidate for 'libmysqlclient-devel-10.0.21-2.15.1.x86_64'. The highest available version is already installed.
Resolving package dependencies...
Nothing to do.

**Comment by peppelinux** [comment]
MySQL-python for python2.7 not for python3.4

**Comment by ZanQdo** [comment]
I got it! doing q "pip install -r requirements.txt" was probably launching py3 so I did a "pip2.7 install -r requirements.txt" in venv root and it worked!

**Comment by ZanQdo** [comment]
I think this can be closed but maybe good to add notice in documentation that it might be necessary to specify pip2.7 :)

Thanks a lot everyone

**Comment by fsiddi** [comment]
Glad to hear this has been sorted out!
