### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by ZanQdo** [armadillica/flamenco#167]
Following the instructions for grut:

grunt-cli@0.1.13 /usr/lib/node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

zanqdo@linux-sao3:~/Downloads/flamenco> sudo npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/home/zanqdo/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 3.16.7-24-desktop
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/zanqdo/Downloads/flamenco
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! path /home/zanqdo/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/zanqdo/Downloads/flamenco/npm-debug.log
npm ERR! not ok code 0

**Comment by fsiddi** [comment]
It looks like you are using an old version of node. Try to get the latest one here https://nodejs.org/en/.

**Comment by ZanQdo** [comment]
@fsiddi I compiled and installed node from source now. Check it out

http://www.pasteall.org/61489

**Comment by peppelinux** [comment]
The problem is that you launch install in a wrong folder, you must launch npm install in $FLAMENCODIR/flamenco/flamenco/dashboard

**Comment by ZanQdo** [comment]
Thanks that did it.
