### ISSUE TITLE
Initial setup of Worker on Windows 10 WindowsError: [Error 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by EVMosaic** [armadillica/flamenco#169]
Setting up a worker on Windows 10 and kept getting 

<code>
Traceback (most recent call last):
  File ".\manage.py", line 4, in <module>
    from application import app
  File "E:\flamenco\flamenco\worker\application\__init__.py", line 44, in <module>
    os.mkdir(tmp_folder)
WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\ericva~1\\appdata\\local\\temp\\flamenco-worker\\ML-LT-24A'
</code>

Spent some time messing with the init.py and it looks like the issues was coming from the use of 

<code>os.mkdir(tmp_folder)</code>

 not being able to create subfolders when it couldn't find the STORAGE_DIR. Changing to 

<code>os.makedirs(tmp_folder)</code>

 resolved the issue for me, and was able to initialize the worker.

**Comment by fsiddi** [comment]
Thanks for reporting!
