### ISSUE TITLE
KeyError: 'port'

### ISSUE THREAD

**Issue by kromar** [armadillica/flamenco#172]
im getting the following error when i want to access the manager on the dashboard:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\SVN\flamenco\flamenco\dashboard\application\controllers\managers.py", line 31, in index
    "4": val['port'],
KeyError: 'port'
```

maybe i missed something in the configuration, all i did is enter the render path for windows when i was asked when i first started the server

**Comment by binarypearl** [comment]
Do you have a config.py defined in the 'manager/application/config.py'?  Thinking there could potentially be a syntax error with the 'PORT = NNNN' line, or somewhat near that line. 

--Shaun

**Comment by kromar** [comment]
i have trieed with a config.py but since it didnt make any difference i have removed it again. but then since i really are not sure what im doing when it comes to networks and such i might have messed up something there. i will look into the configs again and see if i can get past this problem.

**Comment by kromar** [comment]
i looked into the config files but i have no clue whats wrong, no mather what i change i always get the same issue. so what should i look for exactly in the config file to solve this port error?

**Comment by EVMosaic** [comment]
Hey I also ran into this problem. I fixed it with a cheap hack for the time being by hardcoding the port in the managers.py file located at:

`flamenco/flamenco/dashboard/application/controllers/managers.py` 

changing `"4": val['port'],` to `"4":7777,` or whatever port you are using in the following method

```
def index():
    managers = http_server_request('get', '/managers')
    managers_list = []

    for key in managers:
        val = managers[key]
        val['checkbox'] = '<input type="checkbox" value="' \
            + str(val['id']) + ';' + str(val['id']) + '"/>'
        managers_list.append({
            "DT_RowId": "manager_" + str(val['id']),
            "0": val['checkbox'],
            "1": key,
            "2": val['host'],
            "3": val['ip_address'],
            "4": val['port'],
            "5": val['connection'],
            "6": val['id'],
        })
```
makes it work for me. The larger problem seems to be the no port attribute on manager error, and checking `flamenco/flamenco/server/application/modules/managers/model.py` I can see that it does not have a port attribute, but I don't know enough about flask to know how to fix that.

**Comment by kromar** [comment]
hey thanks for this, one step closer to farming:D everything in the dashboard seems to work now but i get a error from the blender addon. i will open a new ticket for that one.

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.

**Comment by muhammad2k18** [comment]
this isn't related to being an obsolete version. i'm facing this error in pycharm 2019 when using flask and pymysql.
