### ISSUE TITLE
Documentation - Flamenco on Docker

### ISSUE THREAD

**Issue by AdmiralPotato** [armadillica/flamenco#174]
I've been watching some of the progress in this repo related to the creation of Docker containers for the server, manager and dashboard take place over the past few days. After having a hard time comprehending and properly configuring the server from the source here on GitHub, I'm hoping that these containers will be a little bit easier to use. I'm excited to try them out, but I'm not seeing any documentation or reference to how to use the containers I see listed here:

https://hub.docker.com/search/?q=flamenco

![docker_flamenco_containers-2015-12-02](https://cloud.githubusercontent.com/assets/820844/11553166/5e86e41c-9949-11e5-937f-f07497cebb62.png)

Following available information on working with Docker, I do at least know how to pull down and run a container, so I try the following to pull down the Server container:
```
$ docker run armadillica/flamenco_server_pro
```

which yields the message:

```
python: can't open file 'manage.py': [Errno 2] No such file or directory
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
```

Not sure what this means, or if these are critical errors. Moving on, I know that the Manager needs to be running as well, so I open another Docker terminal and run the following:
```
$ docker run armadillica/flamenco_manager_pro
```

which yields the following message:

```
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
```

Again, I am not sure what this means, or if these are critical errors. Moving on to the last step(?), I know that the Dashboard needs to be running as well, so I open yet another Docker terminal and  I run the following:
```
$ docker run armadillica/flamenco_dashboard_pro
```

and this is the one that stops me; This command runs a bunch of NPM installs successfully, but then it stops on the following error:

```
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/data/git/dashboard/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.1.13-boot2docker
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /data/git/dashboard
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /data/git/dashboard/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /data/git/dashboard/npm-debug.log
npm ERR! not ok code 0
[05:39:56] Local gulp not found in /data/git/dashboard
[05:39:56] Try running: npm install gulp
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
```

I'm not sure how to proceed, or at my current level of understanding with Docker, how to start troubleshooting something like this in a container yet.

I'm sorry if I'm poking at a feature set that's so bleeding-edge that it's not ready to be used publicly yet, but seeing these Docker images with a few pushes and pulls on them is really exciting for me - I've been looking for a quality personal render queue system to use with Cycles for about 3 years now. May I ask for some guidance and instruction on how to start using the Docker containers to get this tool set up and running?

**Comment by fsiddi** [comment]
Hey there!
I'm sorry that at the moment is still a bit confusing on how to set things up with docker. I'm going to make a more complete install guide in the README.md.
For the moment you find an example docker file here https://github.com/armadillica/flamenco/blob/master/docker/compose/docker-compose-example.yml.

That should at least show the volumes and links that the containers are supposed to have in order to get Flamenco up and running. Let me know if it helps, I'll post an update again when I add a step by step guide on how to setup the docker images.

**Comment by AdmiralPotato** [comment]
You know, I actually tried that a few days after reading your small update to README.md - I copied that file to the directory up from there, renamed it to `docker-compose-example.yml`, ran `docker-compose up` and it seemed to run - but I was actually held up again by a gulp issue where the docker image can't find gulp inside itself.

I would love a bit more information on how to build and use these tools by your process, if you can spare the time. :3

**Comment by fsiddi** [comment]
Hello there! As you might have seen from other issues being closed, I started working on some documentation for the Docker install. It's in the `Readme.md` and should allow you to get up and running. I plan to keep working on it, and make a detailed step-by-step version. Also, I plan to make a quick video. 

If the system is configured properly, it can take as little as 5-10 minutes to get the whole Flamenco infrastructure up and running, so that's a nice goal :)

Let me know if you have questions regarding the readme!

**Comment by PostPollux** [comment]
Cool! I'm looking forward to this short video! Can't wait to use this renderfarm. It looks really nice and I hope it will mature soon.

**Comment by Eibriel** [comment]
I've successfully deployed Flamenco at IdeasFijas following the readme, plus some extra tweaks. I dont know @fsiddi how much detail do you want on the readme, but maybe I can add a step by step   instructions on the Docs.

**Comment by Eibriel** [comment]
![tmp_24098-img_20160206_0854371378283689](https://cloud.githubusercontent.com/assets/172656/12866526/66542a1c-ccaf-11e5-9a6d-376f2efbd672.jpg)

**Comment by fsiddi** [comment]
Hey @Eibriel it's great to hear :)
Feel free to add a step by step intro to the readme. Later on we can refactor it somewhere else.

**Comment by PostPollux** [comment]
Would be very appreciated. Thanks.

**Comment by Eibriel** [comment]
I've updated the Readme, following it step by step should be enough to run Flamenco on Ubuntu 14.04

**Comment by antonvdh** [comment]
I am getting confused do I need to install mysql first?
Readme step:
Mysql container;
Now we start the container, from MySQL Docker image. Keep in mind that Flamenco also works with SQLite and Posgres

anton@Renderfarm:/media/data$ docker run -ti -p 3306:3306 --name mysql -e MySQL_ROOT_PASSWORD=root mysql
error: database is uninitialized and password option is not specified
You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
anton@Renderfarm:/media/data$

**Comment by Eibriel** [comment]
No, the whole thing about Docker is not installing the software on the host machine.
There is a capitalization problem, should be MYSQL_ROOT_PASSWORD instead MYSQL_ROOT_PASSWORD

**Comment by antonvdh** [comment]
Many thanks I feel silly right now, stupid type error .

**Comment by antonvdh** [comment]
How can node workers connect to the manager because the docker ip is a local ip address.
Should I follow now the developer section or where to change?

**Comment by Eibriel** [comment]
The IP address of the Manager is the IP address of the host where the manager docker is running. The port of the manager is 7777

**Comment by antonvdh** [comment]
Can I change this and the server address also because I cannot connect to docker ip 127.17.0.3  number from other nodes and workstations then the local machine.

**Comment by Eibriel** [comment]
The docker "virtual" ip 127.17.0.3 is only reachable from other docker containers, in order to access the manager you should use your host ip 192.xxx.xxx.xxx like address.

On the command:
```
$ docker run -ti -p 7777:7777 --name flamenco_manager --link flamenco_server:flamenco_server --link mysql:mysql \
-v /media/data/flamenco/flamenco/manager:/data/git/manager \
-v /media/data/flamenco_data/storage/shared:/data/storage/shared \
-v /media/data/flamenco_data/storage/manager:/data/storage/manager \
armadillica/flamenco_manager_dev
```

This part: `-p 7777:7777` tells Docker to make accessible that container from the host system.
On the system where you executed that command try accessing to this address from the browser: http://127.0.0.1:7777 , also try: http://127.0.0.1:9999 and http://127.0.0.1:8888 . What do you see?

**Comment by antonvdh** [comment]
All those addresses work fine I see dashboard local worker and server.
But I cannot connect from my workstation with the flamenco plugin. Even if I type in the host address with portnumber.
Also the workers/ other machines need to connect to host/ server ipadress.

**Comment by Eibriel** [comment]
Ok, perfect, what address are you using on the plugin? And what address are you trying to access from other machines?

**Comment by antonvdh** [comment]
The host address in my case 192.168.178.19

For the worker
Should I replace 127.0.0.1 in this line simply by the host ip address.
(venv)$ python /media/data/flamenco/flamenco/worker/run.py --manager 127.0.0.1:7

**Comment by Eibriel** [comment]
For the workers should be: `python /media/data/flamenco/flamenco/worker/run.py --manager 192.168.178.19:7777` (with the virtual environment activated)

For the Addon should be `http://192.168.178.19`

**Comment by antonvdh** [comment]
Ok thanks. That works.
Now I only need to figure out how the flamenco server can autostart when restarting the server.

**Comment by antonvdh** [comment]
Many thanks.

**Comment by Eibriel** [comment]
You are welcome!

I'm closing this now, if there is some problem with the Documentation just open a new Issue.
