### ISSUE TITLE
No gruntfile

### ISSUE THREAD

**Issue by philnelson** [armadillica/flamenco#175]
Running the `grunt` command inside of the dashboard folder, as described in the instructions, returns:

`
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.
`

**Comment by fsiddi** [comment]
Hello there! We are using gulp now, could you tell me where you find indications that you should be using grunt? I'll update them :)

**Comment by philnelson** [comment]
https://github.com/armadillica/flamenco/blob/master/README.md - See "Grunt file for dashboard"

Looks like the docs just weren't updated. Got the dashboard working by installing gulp.

**Comment by fsiddi** [comment]
Great, I will update the README later!

**Comment by antonvdh** [comment]
Please update the Readme.

**Comment by antonvdh** [comment]
Please update the README I had the same error

**Comment by fsiddi** [comment]
Removed grunt in favour of gulp (we are actually using gulp for building the interface). `Readme.md` has been update in 2d6136081d5a8b2c11f283bf8ee5c021f6c9f8d6.
