### ISSUE TITLE
worker missing ./manage.py 

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#178]
How to start the worker there is no manage.py file ?

**Comment by AdmiralPotato** [comment]
+1; This is what I get from the Server and Manager Docker images as they start too.

**Comment by antonvdh** [comment]
sorry do not see what you mean

**Comment by fsiddi** [comment]
There has been a change in functionality (just documented in the ´README.md´), Now the worker is run with:

```
$ python run.py 
```

You can learn more about the options by using the `-h` arg:

```
$ python run.py -h
usage: run.py [-h] [-l LOOP] [-m MANAGER]

Run the Flamenco worker.

optional arguments:
  -h, --help            show this help message and exit
  -l LOOP, --loop LOOP  Loop time. Default is 5 seconds.
  -m MANAGER, --manager MANAGER
                        Manager address. Default is localhost:7777.
```

**Comment by antonvdh** [comment]
Thanks.
I wish you merry christmas and a happy NewYear.

Greetings
Anton
Op 24 dec. 2015 00:40 schreef "Francesco Siddi" <notifications@github.com>:

**Comment by antonvdh** [comment]
Renderfarm works awesome only all my rendered images are send to tmp
instead of the proper path I set within blender 2.76 issue #180



2015-12-24 7:14 GMT+01:00 anton vandehaterd <antonvdh@gmail.com>:
