### ISSUE TITLE
Unable to find local grunt

### ISSUE THREAD

**Issue by jpyams** [armadillica/flamenco#179]
I've followed the instructions in the README.md, and when I get to where it says to run `grunt`, I get this:

    grunt-cli: The grunt command line interface. (v0.1.13)
    
    Fatal error: Unable to find local grunt.
    
    If you're seeing this message, either a Gruntfile wasn't found or grunt
    hasn't been installed locally to your project. For more information about
    installing and configuring grunt, please see the Getting Started guide:
    
    http://gruntjs.com/getting-started

Am I supposed to create a grunt file, or am I not running one of the other commands necessary?

I'm running Linux Mint 17.2 Cinnamon, AMD FX chip.

**Comment by antonvdh** [comment]
See  #175  using Gulp now.

**Comment by fsiddi** [comment]
The `README.md` has finally been updated! So there should be no more misleading mention of grunt anywhere.
