### ISSUE TITLE
output file not working

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#180]
Flamenco renderfarms works but all my rendered images are saved on the server in the tmp file.
I have set the proper output path in blender 2.76 and then choose flamenco tab save and send.

**Comment by antonvdh** [comment]
Please tell if there is a work around for the the output and resolution setting .
Flamenco add on is ignoring the blender 2.67 render settings and all the rendered frames are placed on the server in tmp.

Nobody !

**Comment by Eibriel** [comment]
Flamenco is designed in that way, you need o retrieve the rendered frames from the server.
The resolution will be the same you set on the render preferences, and the format the one selected on the Addon.

**Comment by antonvdh** [comment]
In an earlier version we could from the dashboard add server- project and do path settings. Now we cannot anymore.
If I set the output path in blender to a nfs server should the flamenco plugin render on that place?
If not then all rendered files are placed on the flamenco server under tmp folder which is not accesable from any workstation.
