### ISSUE TITLE
Job appears in dashboard but remains paused

### ISSUE THREAD

**Issue by jpyams** [armadillica/flamenco#181]
I've finally got the dashboard showing and my server, manager, and worker connected.  I also got the addon installed in Blender.

But when I hit "Save and Send" in Blender, the job appears in dashboard as "Paused."  The server and manager appear to be unaware of the job, since they print the same responses over and over again.  The only way the server acknowledges the job is when I delete it.  Otherwise, the job is left waiting.

Running Linux Mint 17.3

**Comment by peppelinux** [comment]
When you submit a new job you have to start it manually from dashboard
have you already done this way ?

**Comment by jpyams** [comment]
Thank you very much!  That worked!
