### ISSUE TITLE
Starting flamenco (docker install)

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#186]
How to restart MySQL container, Server and Dashboard.
Flamenco was up and running before the vm-server has been restared.

**Comment by Eibriel** [comment]
ˋˋˋ
$ sudo docker start mysql
$ sudo docker start flamenco_server
$ sudo docker start flamenco_manager
ˋˋˋ
By the way this is not an issue, is just a question. You may wamt to join us at the #flamemco IRC channel for support.

**Comment by antonvdh** [comment]
Thanks I will add it to my manual.
