### ISSUE TITLE
Integration of other renderers

### ISSUE THREAD

**Issue by eliemichel** [armadillica/flamenco#187]
How much is the Blender-related code isolated from Flamenco's core? Has it been developed with the possibility to eventually extend it to other renderers in mind?

**Comment by fsiddi** [comment]
Blender-related code is quite isolated, although far from perfect. Flamenco was designed to support any type of task (encoding, rendering with any render engine/sw). Are you looking for support for a specific software?

**Comment by eliemichel** [comment]
My first concern is Houdini, but others like Maya or Nuke would be interesting too. I'm considering doing it myself, but first I have to read your code!

**Comment by sybrenstuvel** [comment]
It's great that you want to help supporting other software. Please wait until we've released Flamenco 2.0, which will have an easier to extend command system than the version from Feb 2016.
