### ISSUE TITLE
Job status "paused" after creation

### ISSUE THREAD

**Issue by dkerdudo** [armadillica/flamenco#192]
Hello,

When I "send and pack" my project by Flamenco addon, job is created and visible in dashboard with "paused" status. Worker is still waiting.

So, I need to start or reset the job in dashboard to run the rendering.
In server log, I have this 404 error :

INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:12:53] "GET /tasks/generate?token=323e36461c5a11e693f80242ac110003&worker=node HTTP/1.1" 404 -
INFO:werkzeug:192.168.1.21 - - [18/May/2016 19:12:57] "GET /jobs/8 HTTP/1.1" 200 -
INFO:werkzeug:192.168.1.38 - - [18/May/2016 19:12:57] "GET /jobs/thumbnails/8 HTTP/1.1" 200 -
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:12:58] "GET /tasks/generate?token=323e36461c5a11e693f80242ac110003&worker=node HTTP/1.1" 404 -
**INFO:root:All tasks deleted for job 8**
**INFO:root:Job 8 reset end ready**
INFO:werkzeug:192.168.1.21 - - [18/May/2016 19:13:00] "PUT /jobs HTTP/1.1" 200 -
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:13:03] "GET /tasks/generate?token=323e36461c5a11e693f80242ac110003&worker=node HTTP/1.1" 200 -
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:13:03] "GET /jobs/file/8 HTTP/1.1" 200 -
**INFO:root:Task 80 changed from processing to active**
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:13:03] "PUT /tasks/80 HTTP/1.1" 204 -
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:13:04] "PUT /tasks/80 HTTP/1.1" 204 -
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:13:04] "PUT /tasks/80 HTTP/1.1" 204 -
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:13:04] "PUT /tasks/80 HTTP/1.1" 204 -
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:13:04] "PUT /tasks/80 HTTP/1.1" 204 -
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:13:04] "PUT /tasks/80 HTTP/1.1" 204 -
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:13:04] "PUT /tasks/80 HTTP/1.1" 204 -
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:13:04] "PUT /tasks/80 HTTP/1.1" 204 -
**INFO:root:Task 80 changed from active to completed**
DEBUG:root:0 tasks failed before
INFO:werkzeug:172.17.0.4 - - [18/May/2016 19:13:04] "PUT /tasks/80 HTTP/1.1" 204 -

Is the normal behavior or not ?
How can I start automatically a job's render ?
Thanks.

**Comment by fsiddi** [comment]
Yes, currently new jobs are always created in a `paused` status. That is because we do not have a hook that can be called when the actual file upload is complete (if we would create a job with status `ready`, it could start before the files are actually there).

This is far from ideal, but will be solved in the next version, when the web API becomes more robust.
