### ISSUE TITLE
Tiled render crashes worker.

### ISSUE THREAD

**Issue by chrisw31** [armadillica/flamenco#193]
Hi, I get the following error when doing a tiled render.

Thanks.
Chris.

```
Quering for a new task
New Task Found 10, job 3
Fetching job file 3
Extracting /tmp/flamenco-worker/home-server/3/taskfile_3.zip
Fetching support file 3
Extracting /tmp/flamenco-worker/home-server/3/tasksupportfile_3.zip
Fetching dependency for task 3
No file found
Traceback (most recent call last):
  File "/media/data/flamenco/flamenco/worker/run.py", line 29, in <module>
    worker_loop()
  File "/media/data/flamenco/flamenco/worker/application/controllers.py", line 238, in worker_loop
    execute_task(task, files)
  File "/media/data/flamenco/flamenco/worker/application/controllers.py", line 721, in execute_task
    run_blender_in_thread(options)
  File "/media/data/flamenco/flamenco/worker/application/controllers.py", line 478, in run_blender_in_thread
    "==command==", compiler_settings['commands'][command_name][PLATFORM])
KeyError: 'commands'
```

**Comment by fsiddi** [comment]
Hi,

I'm afraid that for the moment tiled rendering is not working (and nobody is able to support it). We are working on an updated server/manager setup, and we will be able to support this again in a few weeks.

If @Eibriel is up for a workaround on the current codebase maybe we can try to fix this now, but I would prefer to wait.

**Comment by chrisw31** [comment]
Hi, no problem I don't mind waiting a few weeks for the update, I saw comments that people were using it and was wondering if I had made a mistake in the setup.

Thanks very much.
Chris.

**Comment by antonvdh** [comment]
Is tiled rendering supported yet?

**Comment by fsiddi** [comment]
Not yet unfortunately. Will update this task as soon as it happens.

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
