### ISSUE TITLE
How to install Flamenco

### ISSUE THREAD

**Issue by janscherders** [armadillica/flamenco#194]
hi 

I run Blender on Mac OS X and Windows. I would like to try Flamenco but to be honest I really don't understand how to install Flamenco. I am not a technical person and no MySQL knowledge. Is it possible to run Flamenco when you are not a very technical person ? And how to install Flamenco (as I really don't understand the Readme) ?

Best
Jan

**Comment by fsiddi** [comment]
As discussed via email: an update README is planned after merging the pillar-based branch. I'm going to archive this for the moment.
