### ISSUE TITLE
Two Different Versions of Flamenco Available?

### ISSUE THREAD

**Issue by jawwinker** [armadillica/flamenco#195]
Hello,
It seems that there are two different downloads available for Flamenco, and I am doing my best to sort out which one is the most current.  If I download the code with git...

https://github.com/armadillica/flamenco

I see a run.py file in the worker folder.  Whereas if I download from the link on this page...

https://github.com/armadillica/flamenco/releases/tag/v2.0.0-beta.1

There is a manage.py file in the worker file.   

I assume this second file is the deprecated version.  Please advise.

Thanks,
Steve

**Comment by fsiddi** [comment]
Hi Steve,

We are working on a very big update of Flamenco right now. Several things are going to change, so I would advise you to stand by for a few days and check out the project again next week.

**Comment by jawwinker** [comment]
Ooooo!  Exciting!  Thanks for the heads up!

**Comment by sybrenstuvel** [comment]
It has taken more than "a few days", but we're actively working on the new version of Flamenco now. The new Server, Manager and Worker do work now, but with very limited functionality. You also need another Blender Add-on, namely the [Blender Cloud Add-on](https://cloud.blender.org/services#blender-addon), to submit jobs.
