### ISSUE TITLE
Natron and Fusion Support

### ISSUE THREAD

**Issue by tcheng00** [armadillica/flamenco#196]
Hi Guys, 

Looks like a great program.  Was wondering if Natron or Fusion support is coming?

**Comment by sybrenstuvel** [comment]
Hey Tcheng00. Thanks for the interest. So far we're only building support for what we need at the Blender Institute. Once we have a working Blender render pipeline (not far off now), we'll be open for pull requests for supporting other systems. However, that would require an ongoing investment on the part of the person(s) doing the pull request to keep the code up to date, working with the latest master, and writing & maintaining tests.
