### ISSUE TITLE
Overview Thumbnails disappeared

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#197]
Updated my Ubuntu server to 16.04.1 and restarted flamenco.
Now all my thumbnails are disappeared.
![flamenco](https://cloud.githubusercontent.com/assets/1901385/21964180/7c4f80e4-db47-11e6-9958-962e020142c4.png)

**Comment by fsiddi** [comment]
This is a bit generic, so I'm afraid I can't help.
Also, keep in mind that we are working on a new version of Flamenco and the one you are using is no longer supported.

**Comment by antonvdh** [comment]
Ok can't wait to test the new flamenco.
Would be awesome to test this summer!?
