### ISSUE TITLE
Installing new Flamenco - worker install issue

### ISSUE THREAD

**Issue by binarypearl** [armadillica/flamenco#199]
I have been emailing Francesco on getting Flamenco up with using Blender Cloud for the Server.  I figured this is a better spot to post the issues that I am having getting it installed.

I got the Manager installed, and now am trying to get the worker going.

When I run the command: `pip3 install flamenco_worker-2.0.5-py3-none-any.whl`  I get the output below:

rendernavi2 worker # pip3 install flamenco_worker-2.0.5-py3-none-any.whl
Unpacking ./flamenco_worker-2.0.5-py3-none-any.whl
Downloading/unpacking requests>=2.12.4 (from flamenco-worker==2.0.5)
  Downloading requests-2.18.1-py2.py3-none-any.whl (88kB): 88kB downloaded
Requirement already satisfied (use --upgrade to upgrade): attrs>=16.3.0 in /usr/local/lib/python3.4/dist-packages (from flamenco-worker==2.0.5)
Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests>=2.12.4->flamenco-worker==2.0.5)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB): 133kB downloaded
Downloading/unpacking certifi>=2017.4.17 (from requests>=2.12.4->flamenco-worker==2.0.5)
  Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB): 375kB downloaded
Downloading/unpacking idna>=2.5,<2.6 (from requests>=2.12.4->flamenco-worker==2.0.5)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB): 55kB downloaded
Downloading/unpacking urllib3>=1.21.1,<1.22 (from requests>=2.12.4->flamenco-worker==2.0.5)
  Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB): 131kB downloaded
Installing collected packages: flamenco-worker, requests, chardet, certifi, idna, urllib3
*** Error compiling '/tmp/pip-hvyqu5bg-build/flamenco_worker/cli.py'...
  File "/tmp/pip-hvyqu5bg-build/flamenco_worker/cli.py", line 112
    async def stop_loop():
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-hvyqu5bg-build/flamenco_worker/commands.py'...
  File "/tmp/pip-hvyqu5bg-build/flamenco_worker/commands.py", line 87
    async def run(self, settings: dict) -> bool:
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-hvyqu5bg-build/flamenco_worker/may_i_run.py'...
  File "/tmp/pip-hvyqu5bg-build/flamenco_worker/may_i_run.py", line 25
    async def work(self):
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-hvyqu5bg-build/flamenco_worker/runner.py'...
  File "/tmp/pip-hvyqu5bg-build/flamenco_worker/runner.py", line 23
    async def execute(self, task: dict, fworker: worker.FlamencoWorker) -> bool:
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-hvyqu5bg-build/flamenco_worker/upstream.py'...
  File "/tmp/pip-hvyqu5bg-build/flamenco_worker/upstream.py", line 24
    async def get(self, *args, loop, **kwargs) -> requests.Response:
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-hvyqu5bg-build/flamenco_worker/upstream_update_queue.py'...
  File "/tmp/pip-hvyqu5bg-build/flamenco_worker/upstream_update_queue.py", line 58
    async def do_db_push():
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-hvyqu5bg-build/flamenco_worker/worker.py'...
  File "/tmp/pip-hvyqu5bg-build/flamenco_worker/worker.py", line 107
    async def startup(self, *, may_retry_loop=True):
            ^
SyntaxError: invalid syntax

  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: chardet 2.2.1
    Not uninstalling chardet at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: urllib3 1.7.1
    Not uninstalling urllib3 at /usr/lib/python3/dist-packages, owned by OS
Successfully installed flamenco-worker requests chardet certifi idna urllib3
Cleaning up...
rendernavi2 worker # 

---------------------------------------------------------------------------------
Now this does produce a binary:  /usr/local/bin/flamenco-worker

But when I try to run it I get a similar message to the SyntaxError messages above:
foo@rendernavi2 /mnt/backups/blender/flamenco_v2/worker $ /usr/local/bin/flamenco-worker 
Traceback (most recent call last):
  File "/usr/local/bin/flamenco-worker", line 7, in <module>
    from flamenco_worker.cli import main
  File "/usr/local/lib/python3.4/dist-packages/flamenco_worker/cli.py", line 112
    async def stop_loop():
            ^
SyntaxError: invalid syntax
foo@rendernavi2 /mnt/backups/blender/flamenco_v2/worker $ 

Any idea on how to fix this?  If you need more details please let me know, thanks!

--Shaun

**Comment by sybrenstuvel** [comment]
Flamenco Worker needs Python 3.5+; you're using 3.4.

I also recommend installing in a [virtualenv](https://docs.python.org/3.5/library/venv.html), rather than installing system-wide.

**Comment by sybrenstuvel** [comment]
I have updated [the installation documentation](https://www.flamenco.io/docs/user_manual/installation/#flamenco-worker) to reflect this, thanks for reporting.

**Comment by binarypearl** [comment]
Thanks for the info, python 3.5 did solve this issue.  I'm running Linux Mint 17.3, which only has python 3.4.  I installed 3.5 from an external source.  

I'm getting another issue, but now that I have python3.5-venv package installed, I'll try it through a virtualenv first before opening up a new issue.

--Shaun
