### ISSUE TITLE
Forbidden when clicking on 'VIEW LOG' button

### ISSUE THREAD

**Issue by binarypearl** [armadillica/flamenco#203]
This is a minor bug, but when I click on the 'VIEW LOG' button in the Jobs view in https://cloud.blender.org, I get a Forbidden message:

![selection_002](https://user-images.githubusercontent.com/839047/27504220-d691a3aa-5853-11e7-80ff-e6db8c637788.png)

--Shaun

**Comment by sybrenstuvel** [comment]
Please also paste the URL in your description, so that I don't have to copy from a screenshot by hand ;-)

I've solved the issue & deployed it in production.

**Comment by binarypearl** [comment]
Confirmed that this is working, thanks!  

I'll post text from errors/messages/url's etc in the future (and including screenshots if it helps make it more clear).

Unrelated, are you familiar with a technique called OCR (Optical Character Recognition)?  It pulls text out of an image into real text.  I think used the linux package gocr in the past.  I was in a situation once where I had to pull out a hundred or so md5sums of files and copy-paste was explicitly disabled.    

--Shaun

**Comment by sybrenstuvel** [comment]
> Confirmed that this is working, thanks!

Great!

> I'll post text from errors/messages/url's etc in the future (and including screenshots if it helps make it more clear).

👍

> Unrelated, are you familiar with a technique called OCR (Optical Character Recognition)?

Yeah, I know about that. Don't want to use it much, though. In a case like you describe, I usually just get the HTML; even though copying is prohibited in the page, you can always get the content one way or another.
