### ISSUE TITLE
how many PC recommends to run this flamenco , attract , blender cloud thing ?

### ISSUE THREAD

**Issue by haidarvm** [armadillica/flamenco#208]
I like to build IT infrastructure solutions for 3D Animations Production Studio
how many PC need to run this flamenco , attract , blender cloud thing ?
like minimum recommend is 9 PC ?
1 server, 1 dashboard, 2 manager , 4 workers node, 1 NAS ?

I’m about to using supermicro Intel Xeon D-1541 with high performance and low voltage will be better performance per watt

**Comment by sybrenstuvel** [comment]
Flamenco Server and Attract are part of Blender Cloud and already run on our infrastructure.
You need only one Flamenco Manager to manage your local render nodes. How many render nodes you need is heavily project- and budget-dependent. Having a central storage (like a NAS) is indeed recommended too.
