### ISSUE TITLE
armadillica/flamenco_server_dev not found

### ISSUE THREAD

**Issue by ghulamfaqih** [armadillica/flamenco#209]
I have just set up a new cloud server with Ubuntu 16.04, Docker 17.06. and follow installation guide 
https://libraries.io/github/armadillica/flamenco
when im executing  docker run -ti -p 9999:9999 --name flamenco_server, im getting the following error.

"docker: Error response from daemon: repository armadillica/flamenco_server_dev not found: does not exist or no pull access." 
then i try to search flamenco repository in docker https://hub.docker.com/search/ theres no flamenco repisitory.

any help would be greatly appreciated

**Comment by sybrenstuvel** [comment]
That information is obsolete, check the documentation at https://www.flamenco.io/
