### ISSUE TITLE
GPU rendering

### ISSUE THREAD

**Issue by jadbox** [armadillica/flamenco#210]
Using Cycles, is it possible for some slaves to use CPU while others use GPU? Also, how do I specify  a client to explicitly use GPU and set the tile size?

**Comment by sybrenstuvel** [comment]
> is it possible for some slaves to use CPU while others use GPU? 

At this moment, not really, unless you embed an auto-running Python script in the blend file that introspects which worker it's running on and set options accordingly.

> how do I specify a client to explicitly use GPU and set the tile size?

What is a "client"? Just set it in the blend file before saving it.

**Comment by jadbox** [comment]
Thanks for the response. Is Cycles GPU rendering supported at all for network rendering? Are you saying that I just need to change the rendering settings to GPU before switching Blender into network render mode?

**Comment by sybrenstuvel** [comment]
Closing as this is a duplicate of [T54099](https://developer.blender.org/T54099) on our own issue tracker.

I'm also not sure what "switching Blender into network render mode" means.
