### ISSUE TITLE
Feature Request:  Re-queue all failed tasks

### ISSUE THREAD

**Issue by PostPollux** [armadillica/flamenco#218]
A button to re-queue all failed tasks of a job could be very helpful.

I had some cases where the internet connection broke down causing a lot of failed tasks. Now at the moment i have to select one by one and hit "re-queue task". What makes that even more annoying is that the reloading of the page caused by re-queuing a task results in the first page of tasks being loaded. So if all my failed tasks are on page 5, I have to click 4 times on "next" then select the task, hit re-queue and then repeat the whole process for the next task. Pretty cumbersome...

![bugreport](https://user-images.githubusercontent.com/9008901/35277077-c569c18a-0045-11e8-9d12-3840de930b97.png)

**Comment by sybrenstuvel** [comment]
You can just cancel & requeue the job. That will keep the completed tasks and just re-execute the remaining ones.

**Comment by PostPollux** [comment]
Aaaah! Thanks for the tip. I missed that one.
