### ISSUE TITLE
Flamenco worker appends path to Blender filename on Windows 10

### ISSUE THREAD

**Issue by jhowe-3d** [armadillica/flamenco#220]
I can't get Flamenco to render Blender files on my Windows 10 render farm. Everything works well (manager is connecting to server, workers talking to manager) but the filename of the Blender file is getting changed, adding the path to the Flamenco worker to the Blender file path?

My manager is running on MANAGER and the Blender file is in a shared subfolder on that computer. The error I get from the server is 

> Error: Cannot read file 'C:\Flamenco\//MANAGER/Flamenco/2018-02-18-135405.263225-Variable01.flamenco/Variable01.flamenco.blend': No such file or directory

It looks like the Worker, which is installed at C:/Flamenco on all of the render nodes, is appending its own path at the beginning of the Blender file path, resulting in a file not found error. This happens even if I execute the flamenco-worker.exe starting in C:/Flamenco.

How do I configure this so that it doesn't append the worker executable path?

**Comment by sybrenstuvel** [comment]
Map every SMB share you want to use to a drive letter, and use that; instead of using `\\MANAGER\Flamenco` directly, map the share to to `M:` and use `M:/Flamenco`.

**Comment by jhowe-3d** [comment]
Thanks for the help. I had tried to do this before using a common mapped drive and was not successful, so I will show all of the steps I took to get it to work here. First, I mapped the R: drive to \\MANAGER\Flamenco on all render nodes. Inside that I have a JobStorage folder, which I refer to in the flamenco-manager.yaml as

```
  job_storage:
    linux: /shared/
    darwin: /Volume/shared/
    windows: r:/JobStorage/
```

Then I have a SourceFiles folder in the R:/ folder as well, where I put the source files. My user preferences in Blender (image below) specify R:/ as the project path and R:/JobStorage as the job file path.

![user-settings-blender](https://user-images.githubusercontent.com/36255391/36401549-10652f10-15a6-11e8-80c9-b1e3ad305ed5.png)

Something that is really important, is to have forward slashes everywhere. I added them to the end of the job_storage variable, and to the links in the Blender user settings, and then the files started to work properly. What I noticed when things started working properly was the {job_storage} variable in the Flamenco Jobs screen:

![image](https://user-images.githubusercontent.com/36255391/36401669-dad04938-15a6-11e8-8be7-6b4fdd791a7c.png)
 
Overall the setup was pretty easy, but it seems the forward slashes and the job_storage variable are really important. I might suggest adding that as a default or an input field in the flamenco-manager.exe setup.

**Comment by jhowe-3d** [comment]
Pretty excited this is working now! One additional change that I made was in the case where I am running the manager and a worker on the same computer, I can run the worker and set the affinity of the worker to use one less CPU core than I have to make sure the manager is always responsive. To do that, I made a text file called local-render.cmd which contains

```
rem Set affinity to leave one CPU core unused on 16 core system
start "Flamenco Worker" /affinity FFFD "flamenco-worker.exe"
```

and I just link to the local-render.cmd file to launch the worker. Then all child Blender processes inherit that affinity.

**Comment by sybrenstuvel** [comment]
Either ask us to do something (add documentation, add a settings to the web interface, etc.), or close the issue. Not both; "closed" means "closed", and thus we won't look at it again.

> it seems the forward slashes and the job_storage variable are really important.

Forward slashes are mentioned [in the documentation](https://www.flamenco.io/docs/user_manual/installation/#manager-configuration) for a reason ;-)

The trailing slashes aren't important, as Flamenco Manager strips them off anyway.

> I might suggest adding that as a default or an input field in the flamenco-manager.exe setup.

It is actually part of the `flamenco-manager-example.yaml` file, but indeed not in the default settings that Flamenco Manager would write. I've addressed that in commit rFM127d62fb28f6879e7f76ca2081ea0e47fdc35239.
