### ISSUE TITLE
Render status displays

### ISSUE THREAD

**Issue by jhowe-3d** [armadillica/flamenco#222]
On the server, would it be possible to display the following information?

- Average render time per frame
- Number of workers employed
- Estimated time for a job to complete 

I assume that the last value would be average the render time * number of remaining tasks / number of active workers, and would be a general estimate, given how frames can vary from one to the next.

Also, on the manager screen, would it be possible to display the current CPU utilization for each of the Workers? That would let me see at a glance that everyone is assigned and working productively.

**Comment by sybrenstuvel** [comment]
> Average render time per frame

See [T54142](https://developer.blender.org/T54142).

> Number of workers employed

This should be doable.

> Estimated time for a job to complete

This is rather hard to do with any accuracy, as render times can differ from frame to frame, and not all tasks may be render tasks (we also have plans for ffmpeg video encoding tasks, for example). It may be possible, albeit far from trivial, to do this with progressive rendering, assuming that rendering 1000 samples will be 100x more time-consuming than rendering 10 samples.

> Also, on the manager screen, would it be possible to display the current CPU utilization for each of the Workers? That would let me see at a glance that everyone is assigned and working productively.

If you tell me a reliable way to obtain that information in a cross-platform way, it might be possible to squeeze that in with the task updates the Workers send to the Manager.

**Comment by jhowe-3d** [comment]
Agreed that predicting render times is very hard to do. What would likely be easier is to display the render times just for completed tasks. If the chunk size is greater than 1, maybe show the average render time per task or show total time along with chunk size. 

For me the goal would be to quickly identify major issues with a current render job. Really long render times would be a sign of trouble, as would a worker that is not running at full CPU usage. If CPU usage is not feasible, then displaying completed render times would be an improvement. Then we can do our own calculations based as to the time remaining for the job.

Again, a big part of this is just a "sanity check". If I know that frames are going to take 5-7 minutes each to render, then seeing 25 second render results alerts me to the fact that I may have had a problem (layer turned off, for example) and lets me make corrections before running a job overnight or over the weekend.

**Comment by jhowe-3d** [comment]
Just a quick mock-up of what I think would be very helpful displays. Currently we can watch render jobs on the following screen, showing completed, active, and queued tasks:
![flamenco-as-built](https://user-images.githubusercontent.com/36255391/37363943-8cf6310c-26cf-11e8-8c1b-2e7d21bf2ee1.png)
If we could display the total time elapsed for a given task, that gives me a pretty good indicator of the current render "pace":
![flamenco-with-times](https://user-images.githubusercontent.com/36255391/37364160-20ac47ba-26d0-11e8-8c51-877f4bea3d8d.png)
This presents actual elapsed times instead of guessing or estimating the remaining time. With some assumptions about the Blender scene (consistent framing/weight of frames in a scene, for example) I can do some quick math to estimate my completion time. Displaying it as above would let me see how the times are progressing for the tasks without clicking into the detail view and subtracting start and finish times.

**Comment by sybrenstuvel** [comment]
Thanks for the mock-up, it makes things a lot clearer for us :) I think this is a good idea.

**Comment by jhowe-3d** [comment]
This item looks to have been addressed in a recent update, as looking at the task details now gives a great report on render times. Thanks Sybren and Team Flamenco!

![Capture](https://user-images.githubusercontent.com/36255391/55105745-a6cf3700-50a3-11e9-83ad-b8061bb333af.PNG)
