### ISSUE TITLE
Missing Temp Folder in Windows leads to BAM error

### ISSUE THREAD

**Issue by atoav** [armadillica/flamenco#227]
## Problem
I freshly installed the blender cloud addon and was greeted with following message when I tried to render something:  
``` Unable to execute BAM pack: Process stopped with status 1```  

After activating more advanced logging, I managed to hunt down the culpit:
```
 INFO blender_cloud.flamenco.bam_interface   FileNotFoundError: [Errno 2] No usable temporary directory found in ['c:\\temp', 'c:\\tmp', '\\temp', '\\tmp', 'C:\\Program Files\\Blender Foundation\\Blender']
```  

## Solution
I created `c:\\temp` and flamenco started working.

## Possible Fix
- Add better error messages
- Don't assume any of these directories exist (temp directories should be created on demand if they are are not there)

**Comment by fsiddi** [comment]
Hi! Could you please provide which version of the add-on you are using?

**Comment by atoav** [comment]
Not relevant anymore, the missing temp folder was the issue, once I added it, it worked. The error message was a bit hard to read tho.
