### ISSUE TITLE
Unable to connect manager to server - what goes in each config?

### ISSUE THREAD

**Issue by ysguy** [armadillica/flamenco#228]
Hi folks, the documentation on connecting a local master to a local server is vague/lacking.
I've found several config_local.py files for the flamenco folder and the pillar/flamenco/config.py is confusing. If i run python3.6 ./runserver.py runserver without a config_local.py it wont start, if i run it with a config_local.py that i've scraped together it starts but won't allow calls to http://<ip address>:5000:/api however calls to http://<ip address>:5000 return a response, so its obviously doing some things. 

On the manager side, i can start the manager and enter the server URL but it gives 404 errors calling the /api/path/to/stuff for registration (i can grab full url's if needed). 

So i'm confused about SECRET_KEY and the Python generated key and how all these config files work. There seems to be zero documentation i can find about getting this working purely locally.

Any pointers would be greatly appreciated.

**Comment by antonvdh** [comment]
Yes I agree documentation installing flamenco as on-premise server is missing.

**Comment by sybrenstuvel** [comment]
I'd love to see good documentation on this topic. However, since we have many other things to do at the Blender Institute too, we have to prioritise.

**Comment by antonvdh** [comment]
Ok no install then.

**Comment by ysguy** [comment]
Okay we will look at alternate options for now and check back on the project in the future. your response and honesty is appreciated.

**Comment by sybrenstuvel** [comment]
Well, one of the options is to use the Blender Cloud Flamenco server. It's only €10 per month. Out of curiosity, what is your main reason to not use this offer?

**Comment by ysguy** [comment]
The client desires to have a completely off-grid on-premise solution to ensure their content does not leave their premises. Or even the control commands. We have a number of powerful (i7 – dual 1080ti) workstations/render farm stations we want to utilize for blender rendering functions.
