### ISSUE TITLE
Flamenco worker can't find manager

### ISSUE THREAD

**Issue by straaljager** [armadillica/flamenco#236]
Hello, I bought a subscription for Blender Cloud to try out Flamenco in a render farm at work. To test it, both the manager and worker are installed and running on my local machine, however the worker is unable to find the manager, even after specifying the URL of the Flamenco Manager in the config file. Any help appreciated!

> 2020-01-24 09:11:00,795  WARNING flamenco_worker.worker.FlamencoWorker Unable to POST to manager /register-worker, retrying in 30 seconds: 404 Client Error: Not Found for url: http://[flamenco-manager-url]:8080/register-worker; 404 page not found

**Comment by sybrenstuvel** [comment]
It looks like the Flamenco Manager URL hasn't been updated. Have you restarted Flamenco Manager after updating its configuration file? What does it show in the web interface when you go to setup mode?

**Comment by straaljager** [comment]
I restarted Flamenco Manager after updating the worker config file. Tried multiple times, but the result is the same:

<img width="1161" alt="Screenshot 2020-01-24 at 14 02 30" src="https://user-images.githubusercontent.com/13703350/73071145-5e92c800-3eb2-11ea-92c2-b0fda8f1685e.png">

**Comment by straaljager** [comment]
In fact, the Flamenco Manager shows this message: "Setup Mode
Normal operations of this Flamenco Manager have been suspended." 

Maybe that can help identify the culprit.

**Comment by sybrenstuvel** [comment]
That message just means that Flamenco Manager is running in setup mode. In this mode it stops normal operations; the assumption is that you're in setup mode because some setting needs changing, so there is no use in running with the old settings.

Set up Flamenco Manager, save the settings, switch to normal mode. Then it should work.

**Comment by straaljager** [comment]
Indeed, that did the trick, thanks! In fact, the issue was related to not having permissions to run Flamenco manager, so it could not be restarted from the web interface. chmod fixed that, and now I see the worker.
