### ISSUE TITLE
Error on linking Manager to selfhosted Intance of blender-cloud

### ISSUE THREAD

**Issue by jldmn** [armadillica/flamenco#249]
We set up our own version of the blender cloud because we need 100% control of the data for compliance reasons.
Setup of the blender-cloud and blender-id projects have been gone well so far but we are still unable to link managers to our instance.

After selecting the manager we want to register in the cloud panel we get a 400 Error with "The CSRF token is missing." Error Message.

If anyone can help i would be pleased to provide further information.
Thanks in advance.

**Comment by fsiddi** [comment]
Thanks for reporting the issue!
Hopefully @sybrenstuvel can provide some advice in the next days.

**Comment by sybrenstuvel** [comment]
We've been talking on https://blender.chat/channel/flamenco
