### ISSUE TITLE
Flamenco-manager 2.7 Unable to connect to MongoDB

### ISSUE THREAD

**Issue by rickpalo** [armadillica/flamenco#250]
I installed the latest flamenco manager (2.7) on Ubuntu 20.04.1.  After setup and restarting the server, I get the following error:  
"Unable to connect to MongoDB".  See terminal output below.  I used the default easy installation  and I didn't see any configuration to change related to this.  I don't know anything about Mongo.  Any suggestions?  Thanks.
```shell_session
WARN[2020-10-07T21:10:30-06:00] Restarting Flamenco Server                   
INFO[2020-10-07T21:10:30-06:00] Starting Flamenco Manager                     version=v2.7
INFO[2020-10-07T21:10:30-06:00] Run mode                                      mode=production
INFO[2020-10-07T21:10:30-06:00] Flamenco Server URL                           url="https://cloud.blender.org/"
INFO[2020-10-07T21:10:30-06:00] MongoDB executable: /home/.../flamenco/flamenco-manager-2.7/mongodb-linux/bin/mongod 
INFO[2020-10-07T21:10:30-06:00] MongoDB database path: ./db                  
INFO[2020-10-07T21:10:30-06:00] MongoDB will be listening on port 27019      
INFO[2020-10-07T21:10:30-06:00] MongoDB is running at PID 10350              
INFO[2020-10-07T21:10:30-06:00] MongoDB database server                       database_url="mongodb://127.0.0.1:27019/flamanager"
INFO[2020-10-07T21:10:30-06:00] Upstream Flamenco server                      flamenco="https://cloud.blender.org/"
INFO[2020-10-07T21:10:30-06:00] Connecting to MongoDB                         database_url="mongodb://127.0.0.1:27019/flamanager"
ERRO[2020-10-07T21:10:36-06:00] Unable to connect to MongoDB                  database_url="mongodb://127.0.0.1:27019/flamanager" error="no reachable servers"`
```

**Comment by sybrenstuvel** [comment]
It looks like MongoDB is shutting down unexpectedly. Check `mongodb-logs/mongodb.log` in whatever directory you started Flamenco Manager in, that should tell you more. Alternatively, don't use the bundled MongoDB but install it via your Linux distribution's package manager. `sudo apt install mongodb-server` should do the trick. That'll be more stable, for sure.

**Comment by rickpalo** [comment]
Apparently I had a partially installed mongodb, which caused conflicts when manually installing and I assume caused the initial problem.  Purging and re-installing mongodb seems to have it working.  Thanks for your reply!
