### ISSUE TITLE
Blender cloud 403

### ISSUE THREAD

**Issue by Audition-CSBlock** [armadillica/flamenco#264]
I've been trying to figure out this issue on my own but still can't seem to make sense of it, whenever i start the setup of flamenco manager;  
  
I try to connect to the blender cloud for my flamenco server, i log in, and then it shows me a page that says:  
```
Forbidden

You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
```

What am i doing wrong here?

**Comment by sybrenstuvel** [comment]
Please provide us some details.

1. Which URL is giving you that error?
2. Which version of Flamenco Manager are you using?
3. What is your username on Blender Cloud, and do you have a subscription? If you don't want to give that out here in public, that's fine; we can also talk in https://blender.chat/channel/flamenco and pass private information via direct messages.

**Comment by ProductiveAsparagus56** [comment]
I'll provide you with the answers next monday as i am currently away from that particular machine, sorry for this inconvenience.

**Comment by ProductiveAsparagus56** [comment]
1. `https://cloud.blender.org/flamenco/managers/link/choose?hmac=x&identifier=x&return=http%3A%2F%2F10.37.1.170%3A8080%2Fsetup%2Flink-return`
2. 2.7.3
3. I don't have a subscription no, Why would i need to give my username?

**Comment by sybrenstuvel** [comment]
Ah, to use Flamenco on https://cloud.blender.org/ you need to have a Blender Cloud subscription.
