### ISSUE TITLE
Error performing BAT pack after I click submit to Flamenco

### ISSUE THREAD

**Issue by meel-hd** [armadillica/flamenco#273]
Saved "untitled.blend"
bpy.context.scene.flamenco_job_type = 'simple-blender-render'
bpy.context.scene.flamenco_job_settings.frames = "1-20"
bpy.context.scene.flamenco_job_settings.chunk_size = 1
bpy.context.scene.flamenco_job_settings.chunk_size = 2
bpy.context.scene.flamenco_job_settings.chunk_size = 3
bpy.context.scene.flamenco_job_settings.chunk_size = 4
bpy.context.scene.flamenco_job_settings.chunk_size = 5
bpy.context.scene.flamenco_job_settings.render_output_root = ""
bpy.context.space_data.params.directory = "D:\\test\\"
bpy.data.window_managers["WinMan"].(null) = False
bpy.ops.flamenco.submit_job(job_name="untitled")
Error performing BAT pack
bpy.ops.flamenco.submit_job(job_name="untitled")
Error performing BAT pack
bpy.context.scene.flamenco_job_settings.frames = "200-220"
bpy.ops.flamenco.submit_job(job_name="untitled")
Error performing BAT pack

**Comment by Willgheminass** [comment]
I'm also facing this problem today.

**Comment by sybrenstuvel** [comment]
Hey folks. This is likely to be about Flamenco 3 beta. Please report bugs at https://developer.blender.org/maniphest/task/edit/form/14/ and tag them with "Flamenco".

This bug tracker is for the old Flamenco 2, and will be removed from existance soon-ish.

**Comment by b4zz4** [comment]
install python-zstandard
