### ISSUE TITLE
Workers module in server

### ISSUE THREAD

**Issue by fsiddi** [armadillica/flamenco#73]
Since we moved the worker functionality to the Manager, should this module be removed?

**Comment by msimoncz** [comment]
Maybe that would be good, however, how we will handle the worker page on dashboard?

**Comment by fsiddi** [comment]
Well, currently it does not work, right? I think we should get info about a worker by asking the manager, which in turn will get info about the worker (if the worker is non virtual of course).

So shall I go ahead and remove?

**Comment by msimoncz** [comment]
I approve!!

**Comment by cyprusglobe** [comment]
i approve! aswell
