### ISSUE TITLE
UUID update for existing workers

### ISSUE THREAD

**Issue by fsiddi** [armadillica/flamenco#80]
If upon registration with the server the manager is found existing and with a NULL UUID, we should create one. If the manager is already registered with a UUID, we could check if it actually matches.

**Comment by msimoncz** [comment]
What do you think to do if UUIDs does not match?

**Comment by fsiddi** [comment]
I would generate a new UUID on the server and update it in the managers settings (and warn the user about it). This is really meant to be a way for the server to recognise managers, not the other way around.

On a slightly separate topic, we could adopt something similar for the workers too, but not now, we have enough to do.

Let me know if ti sounds good.

**Comment by msimoncz** [comment]
I'm okay with this!!

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
